url: https://dantheand.github.io
baseurl:

# Site settings
title: Daniel A. Anderson
skills: Synthetic Biology - Systems Biology
email: dan.the.anderson@gmail.com
description: "Personal website for Daniel A. Anderson: student, scientist, and overall cool guy."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00ace6
  secondary: 0099cc
  secondary-dark: 333

  #Former Agency Colors
  # primary: fed136
  # secondary: fec503
  # secondary-dark: 333

# Team names, titles and social links
# people:
# - name: Kay Garland
#   pic: 1
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/dantheand
  - title: linkedin
    url: https://www.linkedin.com/in/dantheanderson
  - title: youtube
    url: https://www.youtube.com/channel/UCpA8uC2qZdOcAJ9eqAVaYjw/videos

# Build settings
markdown: kramdown
permalink: pretty
